config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: [ :show, :new, :create ] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.label :comment %>
  <%= f.text_field :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="navbar-lewagon d-flex">
    <div class="d-flex align-items-center">
      <%= image_tag "Popcorn.png", alt: "Watch List Logo", class:"logo"  %>
      <h1 class="fw-bold">Watch List</h1>
    </div>
    <div class="d-flex align-items-center">
      <button class="btn btn-outline-dark me-2 rounded-pill border border-2 shadow-sm">My Lists</button>
      <button class="btn btn-outline-dark me-2 rounded-pill border border-2 shadow-sm">New Lists</button>
    </div>
  </div>
  <div class="banner">
    <h2 class="text-shadow">Make lists of your favourite movies</h2>
    <p class="text-shadow"><em>Sunday Scaries, RomComs etc...</em></p>
  </div>
  <div class="container mt-3 border">
    <div class="d-flex align-items-center justify-content-between py-2 border">
      <button class="btn btn-primary rounded-pill shadow-sm">My Lists</button>
      <button class="btn btn-primary rounded-pill shadow-sm">New Lists</button>
    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/index.html.erb
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%= link_to "Create New List", "lists/new" %>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li><%= "#{Movie.find(bookmark.movie_id).title} - #{bookmark.comment}" %><%= link_to "Delete",
  bookmark_path(bookmark),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%></li>
  <% end %>
</ul>
<%= link_to "Return to Lists", root_path %>

<%= link_to "Add Bookmark", new_list_bookmark_path(params[:id]) %>